# Generated by Django 3.2.4 on 2021-07-05 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserUID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.IntegerField(db_index=True, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['user_uid'],
            },
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Марка автомобиля')),
                ('model', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Модель автомобиля')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год производства автомобиля')),
                ('mileage', models.IntegerField(blank=True, null=True, verbose_name='Пробег автомобиля')),
                ('day_of_car_inspection', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='День осмотра авто')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='car_park.useruid', verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Парк автомобилей',
                'ordering': ['uid'],
            },
        ),
    ]
