# Generated by Django 3.2.4 on 2021-07-21 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя')),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=50, verbose_name='Марка автомобиля')),
                ('model', models.CharField(db_index=True, max_length=128, verbose_name='Модель автомобиля')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год производства автомобиля')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Пользовательское описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления авто в парк')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления данных авто')),
                ('active', models.BooleanField(default=True, verbose_name='Активность или текущее авто в парке')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Парк автомобилей',
                'ordering': ['user', 'id'],
            },
        ),
    ]
