# Generated by Django 3.2.4 on 2021-08-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_park', '0002_auto_20210728_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carhistory',
            options={'ordering': ['mileage', 'date_at'], 'verbose_name': 'Запись истории', 'verbose_name_plural': 'История обслуживания'},
        ),
        migrations.AlterModelOptions(
            name='park',
            options={'ordering': ['user', '-active', '-id'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Парк автомобилей'},
        ),
        migrations.AddField(
            model_name='carhistory',
            name='date_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отметки в истории'),
        ),
        migrations.AlterField(
            model_name='carhistory',
            name='type',
            field=models.CharField(choices=[('INI', 'Первичная запись'), ('F', 'Заправка авто'), ('RGL', 'ТО'), ('RPR', 'Ремонт')], default='F', max_length=3, verbose_name='Тип записи'),
        ),
    ]
